name: GitHub Classroom autograding and update moodle

on:
  workflow_call:
    inputs:
      MOODLE:
        default: false
        required: false
        type: boolean
env:
  DEVOPS_DIR: devops
  GHSECRET: ${{ secrets.GITHUB_TOKEN }}

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  grading:
    # autograding an assignment in GitHub Classroom
    runs-on: ubuntu-latest
    steps:
      - name: Checkout student repo
        uses: actions/checkout@v4
  
      - name: Checkout autograde repo
        uses: actions/checkout@v4
        with:
          repository: ghwalin/autograde_python
          path: autograde
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install flake8 pytest
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
      - name: execute python script
        run: |
          ls -la
          # python3 ./autograde/py_main.py
